#!/bin/bash
rm analyze-abstract.zip
cd ./serverless/analyze-abstract
cd package
zip -r9 ${OLDPWD}/../../function.zip *
cd $OLDPWD
zip -g ../../function.zip lambda_function.py
cd ../..
aws lambda update-function-code --function-name sentiment-analysis-analyze-abstract \
    --zip-file fileb://function.zip